### PR TITLE
grooming temp files, pycache dirs, added .gitignore file

### PR DESCRIPTION
**Pull request by ernestoarbitrio**
- Removed all files with ~ suffix
- Removed `__pycache__` dirs
- Add `.gitignore` file to exlcude mess with git

### CODE REVIEW

**Comment by ernestoarbitrio** [comment]
Linked issue #6

**Review by rjbeers — APPROVED** [review]
I like it. Thanks!

**Comment by rjbeers** [comment]
@drkennetz would you like to do a final review before merging?

**Review by drkennetz — APPROVED** [review]

**Comment by drkennetz** [comment]
Looks good, I like the .gitignore too. Thanks!

**Pull request merged**
